version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports
      - "3000:3000"
